### ISSUE TITLE
Texture sizes?

### ISSUE THREAD

**Issue by iRainDropp** [pipangry/StarLibV2#1]
Ok so this might be a dumb post but I am very confused while following the Docs. I got the .json file working and it changes the form UI in-game but what I don't understand is what the sizes for all the textures should be. It would be nice if there was something about each texture, what the texture size should be & how it's scaled when placed into the menu included somewhere in the docs.

**Comment by pipangry** [comment]
your problem is related to the stretching of the nineslice texture, and not to the work of starlib
