### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by k4ties** [pipangry/StarLibV2#2]
Even i know there's docs, i dont actually know how to make a very basic pack using StarlibV2. I tried to do all like docs said, and i still can't made pack work, yes ik that's issue with ME, but i'm sure in future there will be a lot of people that will have same issue.
I highly recommend to create examples folder and make few example packs to get a small understanding of this all... Thanks.

**Comment by pipangry** [comment]
Hello. **StarLibV2** documentation already contains five full-stack form UI examples, but they are without textures to prevent non-educational use.
It is recommended to start with the **PeanutUI** as the most basic example.
You can see them on the examples tab located in the sidebar.
